server:
  address: ":8002"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# 数据库连接配置
database:
  logger:
    path: "logs/sql"
    level: "all"
    stdout: true
    ctxKeys: ["Trace-Id","UserId","RequestId"]

  default:
    link: "mysql:root:pZO23N*V@tcp(47.96.253.205:3305)/ark_db?loc=Local&parseTime=true"
    debug: true


# Redis 配置示例
redis:
  default:
    address: 47.96.253.205:6379
    db: 4
    pass: "vZYHU3enGTg5Ufi"
    idleTimeout: 600


