// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalActivityRewardForGuildDao is internal type for wrapping internal DAO implements.
type internalActivityRewardForGuildDao = *internal.ActivityRewardForGuildDao

// activityRewardForGuildDao is the data access object for table activity_reward_for_guild.
// You can define custom methods on it to extend its functionality as you wish.
type activityRewardForGuildDao struct {
	internalActivityRewardForGuildDao
}

var (
	// ActivityRewardForGuild is globally public accessible object for table activity_reward_for_guild operations.
	ActivityRewardForGuild = activityRewardForGuildDao{
		internal.NewActivityRewardForGuildDao(),
	}
)

// Fill with you ideas below.
