// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalActivityUserConfigDao is internal type for wrapping internal DAO implements.
type internalActivityUserConfigDao = *internal.ActivityUserConfigDao

// activityUserConfigDao is the data access object for table activity_user_config.
// You can define custom methods on it to extend its functionality as you wish.
type activityUserConfigDao struct {
	internalActivityUserConfigDao
}

var (
	// ActivityUserConfig is globally public accessible object for table activity_user_config operations.
	ActivityUserConfig = activityUserConfigDao{
		internal.NewActivityUserConfigDao(),
	}
)

// Fill with you ideas below.
