// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalActivityPageConfigDao is internal type for wrapping internal DAO implements.
type internalActivityPageConfigDao = *internal.ActivityPageConfigDao

// activityPageConfigDao is the data access object for table activity_page_config.
// You can define custom methods on it to extend its functionality as you wish.
type activityPageConfigDao struct {
	internalActivityPageConfigDao
}

var (
	// ActivityPageConfig is globally public accessible object for table activity_page_config operations.
	ActivityPageConfig = activityPageConfigDao{
		internal.NewActivityPageConfigDao(),
	}
)

// Fill with you ideas below.
