// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalActivityConfigDao is internal type for wrapping internal DAO implements.
type internalActivityConfigDao = *internal.ActivityConfigDao

// activityConfigDao is the data access object for table activity_config.
// You can define custom methods on it to extend its functionality as you wish.
type activityConfigDao struct {
	internalActivityConfigDao
}

var (
	// ActivityConfig is globally public accessible object for table activity_config operations.
	ActivityConfig = activityConfigDao{
		internal.NewActivityConfigDao(),
	}
)

// Fill with you ideas below.
