// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalActivityPlanDao is internal type for wrapping internal DAO implements.
type internalActivityPlanDao = *internal.ActivityPlanDao

// activityPlanDao is the data access object for table activity_plan.
// You can define custom methods on it to extend its functionality as you wish.
type activityPlanDao struct {
	internalActivityPlanDao
}

var (
	// ActivityPlan is globally public accessible object for table activity_plan operations.
	ActivityPlan = activityPlanDao{
		internal.NewActivityPlanDao(),
	}
)

// Fill with you ideas below.
