// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalAgentDetailRecordDao is internal type for wrapping internal DAO implements.
type internalAgentDetailRecordDao = *internal.AgentDetailRecordDao

// agentDetailRecordDao is the data access object for table agent_detail_record.
// You can define custom methods on it to extend its functionality as you wish.
type agentDetailRecordDao struct {
	internalAgentDetailRecordDao
}

var (
	// AgentDetailRecord is globally public accessible object for table agent_detail_record operations.
	AgentDetailRecord = agentDetailRecordDao{
		internal.NewAgentDetailRecordDao(),
	}
)

// Fill with you ideas below.
