// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalAgentBalanceRecordDao is internal type for wrapping internal DAO implements.
type internalAgentBalanceRecordDao = *internal.AgentBalanceRecordDao

// agentBalanceRecordDao is the data access object for table agent_balance_record.
// You can define custom methods on it to extend its functionality as you wish.
type agentBalanceRecordDao struct {
	internalAgentBalanceRecordDao
}

var (
	// AgentBalanceRecord is globally public accessible object for table agent_balance_record operations.
	AgentBalanceRecord = agentBalanceRecordDao{
		internal.NewAgentBalanceRecordDao(),
	}
)

// Fill with you ideas below.
