// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalAgentOperaRecordDao is internal type for wrapping internal DAO implements.
type internalAgentOperaRecordDao = *internal.AgentOperaRecordDao

// agentOperaRecordDao is the data access object for table agent_opera_record.
// You can define custom methods on it to extend its functionality as you wish.
type agentOperaRecordDao struct {
	internalAgentOperaRecordDao
}

var (
	// AgentOperaRecord is globally public accessible object for table agent_opera_record operations.
	AgentOperaRecord = agentOperaRecordDao{
		internal.NewAgentOperaRecordDao(),
	}
)

// Fill with you ideas below.
