// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalAnchorWeekSettlementDao is internal type for wrapping internal DAO implements.
type internalAnchorWeekSettlementDao = *internal.AnchorWeekSettlementDao

// anchorWeekSettlementDao is the data access object for table anchor_week_settlement.
// You can define custom methods on it to extend its functionality as you wish.
type anchorWeekSettlementDao struct {
	internalAnchorWeekSettlementDao
}

var (
	// AnchorWeekSettlement is globally public accessible object for table anchor_week_settlement operations.
	AnchorWeekSettlement = anchorWeekSettlementDao{
		internal.NewAnchorWeekSettlementDao(),
	}
)

// Fill with you ideas below.
