// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalAnchorRankRuleDao is internal type for wrapping internal DAO implements.
type internalAnchorRankRuleDao = *internal.AnchorRankRuleDao

// anchorRankRuleDao is the data access object for table anchor_rank_rule.
// You can define custom methods on it to extend its functionality as you wish.
type anchorRankRuleDao struct {
	internalAnchorRankRuleDao
}

var (
	// AnchorRankRule is globally public accessible object for table anchor_rank_rule operations.
	AnchorRankRule = anchorRankRuleDao{
		internal.NewAnchorRankRuleDao(),
	}
)

// Fill with you ideas below.
