// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalAnchorLevelDao is internal type for wrapping internal DAO implements.
type internalAnchorLevelDao = *internal.AnchorLevelDao

// anchorLevelDao is the data access object for table anchor_level.
// You can define custom methods on it to extend its functionality as you wish.
type anchorLevelDao struct {
	internalAnchorLevelDao
}

var (
	// AnchorLevel is globally public accessible object for table anchor_level operations.
	AnchorLevel = anchorLevelDao{
		internal.NewAnchorLevelDao(),
	}
)

// Fill with you ideas below.
