// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalAnchorDayStatisticsDao is internal type for wrapping internal DAO implements.
type internalAnchorDayStatisticsDao = *internal.AnchorDayStatisticsDao

// anchorDayStatisticsDao is the data access object for table anchor_day_statistics.
// You can define custom methods on it to extend its functionality as you wish.
type anchorDayStatisticsDao struct {
	internalAnchorDayStatisticsDao
}

var (
	// AnchorDayStatistics is globally public accessible object for table anchor_day_statistics operations.
	AnchorDayStatistics = anchorDayStatisticsDao{
		internal.NewAnchorDayStatisticsDao(),
	}
)

// Fill with you ideas below.
