// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalAnchorLabelApplyDao is internal type for wrapping internal DAO implements.
type internalAnchorLabelApplyDao = *internal.AnchorLabelApplyDao

// anchorLabelApplyDao is the data access object for table anchor_label_apply.
// You can define custom methods on it to extend its functionality as you wish.
type anchorLabelApplyDao struct {
	internalAnchorLabelApplyDao
}

var (
	// AnchorLabelApply is globally public accessible object for table anchor_label_apply operations.
	AnchorLabelApply = anchorLabelApplyDao{
		internal.NewAnchorLabelApplyDao(),
	}
)

// Fill with you ideas below.
