// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalAppConfigDao is internal type for wrapping internal DAO implements.
type internalAppConfigDao = *internal.AppConfigDao

// appConfigDao is the data access object for table app_config.
// You can define custom methods on it to extend its functionality as you wish.
type appConfigDao struct {
	internalAppConfigDao
}

var (
	// AppConfig is globally public accessible object for table app_config operations.
	AppConfig = appConfigDao{
		internal.NewAppConfigDao(),
	}
)

// Fill with you ideas below.
