// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalApplyBattleDao is internal type for wrapping internal DAO implements.
type internalApplyBattleDao = *internal.ApplyBattleDao

// applyBattleDao is the data access object for table apply_battle.
// You can define custom methods on it to extend its functionality as you wish.
type applyBattleDao struct {
	internalApplyBattleDao
}

var (
	// ApplyBattle is globally public accessible object for table apply_battle operations.
	ApplyBattle = applyBattleDao{
		internal.NewApplyBattleDao(),
	}
)

// Fill with you ideas below.
