// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalAreaInfoDao is internal type for wrapping internal DAO implements.
type internalAreaInfoDao = *internal.AreaInfoDao

// areaInfoDao is the data access object for table area_info.
// You can define custom methods on it to extend its functionality as you wish.
type areaInfoDao struct {
	internalAreaInfoDao
}

var (
	// AreaInfo is globally public accessible object for table area_info operations.
	AreaInfo = areaInfoDao{
		internal.NewAreaInfoDao(),
	}
)

// Fill with you ideas below.
