// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalBalanceRecordDao is internal type for wrapping internal DAO implements.
type internalBalanceRecordDao = *internal.BalanceRecordDao

// balanceRecordDao is the data access object for table balance_record.
// You can define custom methods on it to extend its functionality as you wish.
type balanceRecordDao struct {
	internalBalanceRecordDao
}

var (
	// BalanceRecord is globally public accessible object for table balance_record operations.
	BalanceRecord = balanceRecordDao{
		internal.NewBalanceRecordDao(),
	}
)

// Fill with you ideas below.
