// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalBalanceStatisticsUserDao is internal type for wrapping internal DAO implements.
type internalBalanceStatisticsUserDao = *internal.BalanceStatisticsUserDao

// balanceStatisticsUserDao is the data access object for table balance_statistics_user.
// You can define custom methods on it to extend its functionality as you wish.
type balanceStatisticsUserDao struct {
	internalBalanceStatisticsUserDao
}

var (
	// BalanceStatisticsUser is globally public accessible object for table balance_statistics_user operations.
	BalanceStatisticsUser = balanceStatisticsUserDao{
		internal.NewBalanceStatisticsUserDao(),
	}
)

// Fill with you ideas below.
