// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalBattleMatchRecordDao is internal type for wrapping internal DAO implements.
type internalBattleMatchRecordDao = *internal.BattleMatchRecordDao

// battleMatchRecordDao is the data access object for table battle_match_record.
// You can define custom methods on it to extend its functionality as you wish.
type battleMatchRecordDao struct {
	internalBattleMatchRecordDao
}

var (
	// BattleMatchRecord is globally public accessible object for table battle_match_record operations.
	BattleMatchRecord = battleMatchRecordDao{
		internal.NewBattleMatchRecordDao(),
	}
)

// Fill with you ideas below.
