// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalBeautifulNumClassifyDao is internal type for wrapping internal DAO implements.
type internalBeautifulNumClassifyDao = *internal.BeautifulNumClassifyDao

// beautifulNumClassifyDao is the data access object for table beautiful_num_classify.
// You can define custom methods on it to extend its functionality as you wish.
type beautifulNumClassifyDao struct {
	internalBeautifulNumClassifyDao
}

var (
	// BeautifulNumClassify is globally public accessible object for table beautiful_num_classify operations.
	BeautifulNumClassify = beautifulNumClassifyDao{
		internal.NewBeautifulNumClassifyDao(),
	}
)

// Fill with you ideas below.
