// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalBeautifulNumDao is internal type for wrapping internal DAO implements.
type internalBeautifulNumDao = *internal.BeautifulNumDao

// beautifulNumDao is the data access object for table beautiful_num.
// You can define custom methods on it to extend its functionality as you wish.
type beautifulNumDao struct {
	internalBeautifulNumDao
}

var (
	// BeautifulNum is globally public accessible object for table beautiful_num operations.
	BeautifulNum = beautifulNumDao{
		internal.NewBeautifulNumDao(),
	}
)

// Fill with you ideas below.
