// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalBlackListDao is internal type for wrapping internal DAO implements.
type internalBlackListDao = *internal.BlackListDao

// blackListDao is the data access object for table black_list.
// You can define custom methods on it to extend its functionality as you wish.
type blackListDao struct {
	internalBlackListDao
}

var (
	// BlackList is globally public accessible object for table black_list operations.
	BlackList = blackListDao{
		internal.NewBlackListDao(),
	}
)

// Fill with you ideas below.
