// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalCharmAnchorDayStatisticsDao is internal type for wrapping internal DAO implements.
type internalCharmAnchorDayStatisticsDao = *internal.CharmAnchorDayStatisticsDao

// charmAnchorDayStatisticsDao is the data access object for table charm_anchor_day_statistics.
// You can define custom methods on it to extend its functionality as you wish.
type charmAnchorDayStatisticsDao struct {
	internalCharmAnchorDayStatisticsDao
}

var (
	// CharmAnchorDayStatistics is globally public accessible object for table charm_anchor_day_statistics operations.
	CharmAnchorDayStatistics = charmAnchorDayStatisticsDao{
		internal.NewCharmAnchorDayStatisticsDao(),
	}
)

// Fill with you ideas below.
