// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalCommodityInfoDao is internal type for wrapping internal DAO implements.
type internalCommodityInfoDao = *internal.CommodityInfoDao

// commodityInfoDao is the data access object for table commodity_info.
// You can define custom methods on it to extend its functionality as you wish.
type commodityInfoDao struct {
	internalCommodityInfoDao
}

var (
	// CommodityInfo is globally public accessible object for table commodity_info operations.
	CommodityInfo = commodityInfoDao{
		internal.NewCommodityInfoDao(),
	}
)

// Fill with you ideas below.
