// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalCommodityFreeGiftDao is internal type for wrapping internal DAO implements.
type internalCommodityFreeGiftDao = *internal.CommodityFreeGiftDao

// commodityFreeGiftDao is the data access object for table commodity_free_gift.
// You can define custom methods on it to extend its functionality as you wish.
type commodityFreeGiftDao struct {
	internalCommodityFreeGiftDao
}

var (
	// CommodityFreeGift is globally public accessible object for table commodity_free_gift operations.
	CommodityFreeGift = commodityFreeGiftDao{
		internal.NewCommodityFreeGiftDao(),
	}
)

// Fill with you ideas below.
