// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalComplexPrizeRecordDao is internal type for wrapping internal DAO implements.
type internalComplexPrizeRecordDao = *internal.ComplexPrizeRecordDao

// complexPrizeRecordDao is the data access object for table complex_prize_record.
// You can define custom methods on it to extend its functionality as you wish.
type complexPrizeRecordDao struct {
	internalComplexPrizeRecordDao
}

var (
	// ComplexPrizeRecord is globally public accessible object for table complex_prize_record operations.
	ComplexPrizeRecord = complexPrizeRecordDao{
		internal.NewComplexPrizeRecordDao(),
	}
)

// Fill with you ideas below.
