// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalDiamondTurntableRecordDao is internal type for wrapping internal DAO implements.
type internalDiamondTurntableRecordDao = *internal.DiamondTurntableRecordDao

// diamondTurntableRecordDao is the data access object for table diamond_turntable_record.
// You can define custom methods on it to extend its functionality as you wish.
type diamondTurntableRecordDao struct {
	internalDiamondTurntableRecordDao
}

var (
	// DiamondTurntableRecord is globally public accessible object for table diamond_turntable_record operations.
	DiamondTurntableRecord = diamondTurntableRecordDao{
		internal.NewDiamondTurntableRecordDao(),
	}
)

// Fill with you ideas below.
