// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalFeedMarkDao is internal type for wrapping internal DAO implements.
type internalFeedMarkDao = *internal.FeedMarkDao

// feedMarkDao is the data access object for table feed_mark.
// You can define custom methods on it to extend its functionality as you wish.
type feedMarkDao struct {
	internalFeedMarkDao
}

var (
	// FeedMark is globally public accessible object for table feed_mark operations.
	FeedMark = feedMarkDao{
		internal.NewFeedMarkDao(),
	}
)

// Fill with you ideas below.
