// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalFeedInfoDao is internal type for wrapping internal DAO implements.
type internalFeedInfoDao = *internal.FeedInfoDao

// feedInfoDao is the data access object for table feed_info.
// You can define custom methods on it to extend its functionality as you wish.
type feedInfoDao struct {
	internalFeedInfoDao
}

var (
	// FeedInfo is globally public accessible object for table feed_info operations.
	FeedInfo = feedInfoDao{
		internal.NewFeedInfoDao(),
	}
)

// Fill with you ideas below.
