// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalFeedTopicDao is internal type for wrapping internal DAO implements.
type internalFeedTopicDao = *internal.FeedTopicDao

// feedTopicDao is the data access object for table feed_topic.
// You can define custom methods on it to extend its functionality as you wish.
type feedTopicDao struct {
	internalFeedTopicDao
}

var (
	// FeedTopic is globally public accessible object for table feed_topic operations.
	FeedTopic = feedTopicDao{
		internal.NewFeedTopicDao(),
	}
)

// Fill with you ideas below.
