// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalGameConfigDao is internal type for wrapping internal DAO implements.
type internalGameConfigDao = *internal.GameConfigDao

// gameConfigDao is the data access object for table game_config.
// You can define custom methods on it to extend its functionality as you wish.
type gameConfigDao struct {
	internalGameConfigDao
}

var (
	// GameConfig is globally public accessible object for table game_config operations.
	GameConfig = gameConfigDao{
		internal.NewGameConfigDao(),
	}
)

// Fill with you ideas below.
