// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalGameRoomStatisticsDao is internal type for wrapping internal DAO implements.
type internalGameRoomStatisticsDao = *internal.GameRoomStatisticsDao

// gameRoomStatisticsDao is the data access object for table game_room_statistics.
// You can define custom methods on it to extend its functionality as you wish.
type gameRoomStatisticsDao struct {
	internalGameRoomStatisticsDao
}

var (
	// GameRoomStatistics is globally public accessible object for table game_room_statistics operations.
	GameRoomStatistics = gameRoomStatisticsDao{
		internal.NewGameRoomStatisticsDao(),
	}
)

// Fill with you ideas below.
