// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalGameStatisticsDao is internal type for wrapping internal DAO implements.
type internalGameStatisticsDao = *internal.GameStatisticsDao

// gameStatisticsDao is the data access object for table game_statistics.
// You can define custom methods on it to extend its functionality as you wish.
type gameStatisticsDao struct {
	internalGameStatisticsDao
}

var (
	// GameStatistics is globally public accessible object for table game_statistics operations.
	GameStatistics = gameStatisticsDao{
		internal.NewGameStatisticsDao(),
	}
)

// Fill with you ideas below.
