// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalGiftLogDao is internal type for wrapping internal DAO implements.
type internalGiftLogDao = *internal.GiftLogDao

// giftLogDao is the data access object for table gift_log.
// You can define custom methods on it to extend its functionality as you wish.
type giftLogDao struct {
	internalGiftLogDao
}

var (
	// GiftLog is globally public accessible object for table gift_log operations.
	GiftLog = giftLogDao{
		internal.NewGiftLogDao(),
	}
)

// Fill with you ideas below.
