// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalGiftLuckyLogDao is internal type for wrapping internal DAO implements.
type internalGiftLuckyLogDao = *internal.GiftLuckyLogDao

// giftLuckyLogDao is the data access object for table gift_lucky_log.
// You can define custom methods on it to extend its functionality as you wish.
type giftLuckyLogDao struct {
	internalGiftLuckyLogDao
}

var (
	// GiftLuckyLog is globally public accessible object for table gift_lucky_log operations.
	GiftLuckyLog = giftLuckyLogDao{
		internal.NewGiftLuckyLogDao(),
	}
)

// Fill with you ideas below.
