// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalGoogleOrderDao is internal type for wrapping internal DAO implements.
type internalGoogleOrderDao = *internal.GoogleOrderDao

// googleOrderDao is the data access object for table google_order.
// You can define custom methods on it to extend its functionality as you wish.
type googleOrderDao struct {
	internalGoogleOrderDao
}

var (
	// GoogleOrder is globally public accessible object for table google_order operations.
	GoogleOrder = googleOrderDao{
		internal.NewGoogleOrderDao(),
	}
)

// Fill with you ideas below.
