// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalGuildPullGuildInfoDao is internal type for wrapping internal DAO implements.
type internalGuildPullGuildInfoDao = *internal.GuildPullGuildInfoDao

// guildPullGuildInfoDao is the data access object for table guild_pull_guild_info.
// You can define custom methods on it to extend its functionality as you wish.
type guildPullGuildInfoDao struct {
	internalGuildPullGuildInfoDao
}

var (
	// GuildPullGuildInfo is globally public accessible object for table guild_pull_guild_info operations.
	GuildPullGuildInfo = guildPullGuildInfoDao{
		internal.NewGuildPullGuildInfoDao(),
	}
)

// Fill with you ideas below.
