// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalGuildWeekStatisticsDao is internal type for wrapping internal DAO implements.
type internalGuildWeekStatisticsDao = *internal.GuildWeekStatisticsDao

// guildWeekStatisticsDao is the data access object for table guild_week_statistics.
// You can define custom methods on it to extend its functionality as you wish.
type guildWeekStatisticsDao struct {
	internalGuildWeekStatisticsDao
}

var (
	// GuildWeekStatistics is globally public accessible object for table guild_week_statistics operations.
	GuildWeekStatistics = guildWeekStatisticsDao{
		internal.NewGuildWeekStatisticsDao(),
	}
)

// Fill with you ideas below.
