// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"

	"fuya-ark/internal/dao/internal"
	"fuya-ark/internal/model/entity"
)

// internalGuildAnchorDao is internal type for wrapping internal DAO implements.
type internalGuildAnchorDao = *internal.GuildAnchorDao

// guildAnchorDao is the data access object for table guild_anchor.
// You can define custom methods on it to extend its functionality as you wish.
type guildAnchorDao struct {
	internalGuildAnchorDao
}

var (
	// GuildAnchor is globally public accessible object for table guild_anchor operations.
	GuildAnchor = guildAnchorDao{
		internal.NewGuildAnchorDao(),
	}
)

// Fill with you ideas below.

func (m *guildAnchorDao) GetGuildAnchor(ctx context.Context, userId int64, status int) (
	data *entity.GuildAnchor, err error) {
	err = g.DB().Model(GuildAnchor.Table()).Ctx(ctx).
		Where("user_id", userId).
		Where("status", status).
		//Cache(gdb.CacheOption{
		//	Duration: time.Hour, Name: cache.MysqlAnchorGuildByUserId + gconv.String(userId) + gconv.String(status)},
		//).
		Scan(&data)
	return data, err
}
