// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalGuildWeekSettlementDao is internal type for wrapping internal DAO implements.
type internalGuildWeekSettlementDao = *internal.GuildWeekSettlementDao

// guildWeekSettlementDao is the data access object for table guild_week_settlement.
// You can define custom methods on it to extend its functionality as you wish.
type guildWeekSettlementDao struct {
	internalGuildWeekSettlementDao
}

var (
	// GuildWeekSettlement is globally public accessible object for table guild_week_settlement operations.
	GuildWeekSettlement = guildWeekSettlementDao{
		internal.NewGuildWeekSettlementDao(),
	}
)

// Fill with you ideas below.
