// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalGuildInfoDao is internal type for wrapping internal DAO implements.
type internalGuildInfoDao = *internal.GuildInfoDao

// guildInfoDao is the data access object for table guild_info.
// You can define custom methods on it to extend its functionality as you wish.
type guildInfoDao struct {
	internalGuildInfoDao
}

var (
	// GuildInfo is globally public accessible object for table guild_info operations.
	GuildInfo = guildInfoDao{
		internal.NewGuildInfoDao(),
	}
)

// Fill with you ideas below.
