// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalInviterInfoDao is internal type for wrapping internal DAO implements.
type internalInviterInfoDao = *internal.InviterInfoDao

// inviterInfoDao is the data access object for table inviter_info.
// You can define custom methods on it to extend its functionality as you wish.
type inviterInfoDao struct {
	internalInviterInfoDao
}

var (
	// InviterInfo is globally public accessible object for table inviter_info operations.
	InviterInfo = inviterInfoDao{
		internal.NewInviterInfoDao(),
	}
)

// Fill with you ideas below.
