// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalLiveClassifyLangDao is internal type for wrapping internal DAO implements.
type internalLiveClassifyLangDao = *internal.LiveClassifyLangDao

// liveClassifyLangDao is the data access object for table live_classify_lang.
// You can define custom methods on it to extend its functionality as you wish.
type liveClassifyLangDao struct {
	internalLiveClassifyLangDao
}

var (
	// LiveClassifyLang is globally public accessible object for table live_classify_lang operations.
	LiveClassifyLang = liveClassifyLangDao{
		internal.NewLiveClassifyLangDao(),
	}
)

// Fill with you ideas below.
