// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalLiveClassifyDao is internal type for wrapping internal DAO implements.
type internalLiveClassifyDao = *internal.LiveClassifyDao

// liveClassifyDao is the data access object for table live_classify.
// You can define custom methods on it to extend its functionality as you wish.
type liveClassifyDao struct {
	internalLiveClassifyDao
}

var (
	// LiveClassify is globally public accessible object for table live_classify operations.
	LiveClassify = liveClassifyDao{
		internal.NewLiveClassifyDao(),
	}
)

// Fill with you ideas below.
