// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalLiveCloudVideoDao is internal type for wrapping internal DAO implements.
type internalLiveCloudVideoDao = *internal.LiveCloudVideoDao

// liveCloudVideoDao is the data access object for table live_cloud_video.
// You can define custom methods on it to extend its functionality as you wish.
type liveCloudVideoDao struct {
	internalLiveCloudVideoDao
}

var (
	// LiveCloudVideo is globally public accessible object for table live_cloud_video operations.
	LiveCloudVideo = liveCloudVideoDao{
		internal.NewLiveCloudVideoDao(),
	}
)

// Fill with you ideas below.
