// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalLoginRecordDao is internal type for wrapping internal DAO implements.
type internalLoginRecordDao = *internal.LoginRecordDao

// loginRecordDao is the data access object for table login_record.
// You can define custom methods on it to extend its functionality as you wish.
type loginRecordDao struct {
	internalLoginRecordDao
}

var (
	// LoginRecord is globally public accessible object for table login_record operations.
	LoginRecord = loginRecordDao{
		internal.NewLoginRecordDao(),
	}
)

// Fill with you ideas below.
