// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalManagerMessageRecordDao is internal type for wrapping internal DAO implements.
type internalManagerMessageRecordDao = *internal.ManagerMessageRecordDao

// managerMessageRecordDao is the data access object for table manager_message_record.
// You can define custom methods on it to extend its functionality as you wish.
type managerMessageRecordDao struct {
	internalManagerMessageRecordDao
}

var (
	// ManagerMessageRecord is globally public accessible object for table manager_message_record operations.
	ManagerMessageRecord = managerMessageRecordDao{
		internal.NewManagerMessageRecordDao(),
	}
)

// Fill with you ideas below.
