// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalMedalInfoDao is internal type for wrapping internal DAO implements.
type internalMedalInfoDao = *internal.MedalInfoDao

// medalInfoDao is the data access object for table medal_info.
// You can define custom methods on it to extend its functionality as you wish.
type medalInfoDao struct {
	internalMedalInfoDao
}

var (
	// MedalInfo is globally public accessible object for table medal_info operations.
	MedalInfo = medalInfoDao{
		internal.NewMedalInfoDao(),
	}
)

// Fill with you ideas below.
