// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalMedalUserDao is internal type for wrapping internal DAO implements.
type internalMedalUserDao = *internal.MedalUserDao

// medalUserDao is the data access object for table medal_user.
// You can define custom methods on it to extend its functionality as you wish.
type medalUserDao struct {
	internalMedalUserDao
}

var (
	// MedalUser is globally public accessible object for table medal_user operations.
	MedalUser = medalUserDao{
		internal.NewMedalUserDao(),
	}
)

// Fill with you ideas below.
