// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalMessageInfoDao is internal type for wrapping internal DAO implements.
type internalMessageInfoDao = *internal.MessageInfoDao

// messageInfoDao is the data access object for table message_info.
// You can define custom methods on it to extend its functionality as you wish.
type messageInfoDao struct {
	internalMessageInfoDao
}

var (
	// MessageInfo is globally public accessible object for table message_info operations.
	MessageInfo = messageInfoDao{
		internal.NewMessageInfoDao(),
	}
)

// Fill with you ideas below.
