// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalNoblePrivilegeDao is internal type for wrapping internal DAO implements.
type internalNoblePrivilegeDao = *internal.NoblePrivilegeDao

// noblePrivilegeDao is the data access object for table noble_privilege.
// You can define custom methods on it to extend its functionality as you wish.
type noblePrivilegeDao struct {
	internalNoblePrivilegeDao
}

var (
	// NoblePrivilege is globally public accessible object for table noble_privilege operations.
	NoblePrivilege = noblePrivilegeDao{
		internal.NewNoblePrivilegeDao(),
	}
)

// Fill with you ideas below.
