// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalNobleInfoDao is internal type for wrapping internal DAO implements.
type internalNobleInfoDao = *internal.NobleInfoDao

// nobleInfoDao is the data access object for table noble_info.
// You can define custom methods on it to extend its functionality as you wish.
type nobleInfoDao struct {
	internalNobleInfoDao
}

var (
	// NobleInfo is globally public accessible object for table noble_info operations.
	NobleInfo = nobleInfoDao{
		internal.NewNobleInfoDao(),
	}
)

// Fill with you ideas below.
