// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalNobleConfigDao is internal type for wrapping internal DAO implements.
type internalNobleConfigDao = *internal.NobleConfigDao

// nobleConfigDao is the data access object for table noble_config.
// You can define custom methods on it to extend its functionality as you wish.
type nobleConfigDao struct {
	internalNobleConfigDao
}

var (
	// NobleConfig is globally public accessible object for table noble_config operations.
	NobleConfig = nobleConfigDao{
		internal.NewNobleConfigDao(),
	}
)

// Fill with you ideas below.
