// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalNobleUserDao is internal type for wrapping internal DAO implements.
type internalNobleUserDao = *internal.NobleUserDao

// nobleUserDao is the data access object for table noble_user.
// You can define custom methods on it to extend its functionality as you wish.
type nobleUserDao struct {
	internalNobleUserDao
}

var (
	// NobleUser is globally public accessible object for table noble_user operations.
	NobleUser = nobleUserDao{
		internal.NewNobleUserDao(),
	}
)

// Fill with you ideas below.
