// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalOrderStatisticsDao is internal type for wrapping internal DAO implements.
type internalOrderStatisticsDao = *internal.OrderStatisticsDao

// orderStatisticsDao is the data access object for table order_statistics.
// You can define custom methods on it to extend its functionality as you wish.
type orderStatisticsDao struct {
	internalOrderStatisticsDao
}

var (
	// OrderStatistics is globally public accessible object for table order_statistics operations.
	OrderStatistics = orderStatisticsDao{
		internal.NewOrderStatisticsDao(),
	}
)

// Fill with you ideas below.
