// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalPaymentInfoDao is internal type for wrapping internal DAO implements.
type internalPaymentInfoDao = *internal.PaymentInfoDao

// paymentInfoDao is the data access object for table payment_info.
// You can define custom methods on it to extend its functionality as you wish.
type paymentInfoDao struct {
	internalPaymentInfoDao
}

var (
	// PaymentInfo is globally public accessible object for table payment_info operations.
	PaymentInfo = paymentInfoDao{
		internal.NewPaymentInfoDao(),
	}
)

// Fill with you ideas below.
