// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalPayoutRecordDao is internal type for wrapping internal DAO implements.
type internalPayoutRecordDao = *internal.PayoutRecordDao

// payoutRecordDao is the data access object for table payout_record.
// You can define custom methods on it to extend its functionality as you wish.
type payoutRecordDao struct {
	internalPayoutRecordDao
}

var (
	// PayoutRecord is globally public accessible object for table payout_record operations.
	PayoutRecord = payoutRecordDao{
		internal.NewPayoutRecordDao(),
	}
)

// Fill with you ideas below.
