// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalPrizeCashbackConfigDao is internal type for wrapping internal DAO implements.
type internalPrizeCashbackConfigDao = *internal.PrizeCashbackConfigDao

// prizeCashbackConfigDao is the data access object for table prize_cashback_config.
// You can define custom methods on it to extend its functionality as you wish.
type prizeCashbackConfigDao struct {
	internalPrizeCashbackConfigDao
}

var (
	// PrizeCashbackConfig is globally public accessible object for table prize_cashback_config operations.
	PrizeCashbackConfig = prizeCashbackConfigDao{
		internal.NewPrizeCashbackConfigDao(),
	}
)

// Fill with you ideas below.
