// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalPrizePoolConfigDao is internal type for wrapping internal DAO implements.
type internalPrizePoolConfigDao = *internal.PrizePoolConfigDao

// prizePoolConfigDao is the data access object for table prize_pool_config.
// You can define custom methods on it to extend its functionality as you wish.
type prizePoolConfigDao struct {
	internalPrizePoolConfigDao
}

var (
	// PrizePoolConfig is globally public accessible object for table prize_pool_config operations.
	PrizePoolConfig = prizePoolConfigDao{
		internal.NewPrizePoolConfigDao(),
	}
)

// Fill with you ideas below.
