// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalQuestPrizeDao is internal type for wrapping internal DAO implements.
type internalQuestPrizeDao = *internal.QuestPrizeDao

// questPrizeDao is the data access object for table quest_prize.
// You can define custom methods on it to extend its functionality as you wish.
type questPrizeDao struct {
	internalQuestPrizeDao
}

var (
	// QuestPrize is globally public accessible object for table quest_prize operations.
	QuestPrize = questPrizeDao{
		internal.NewQuestPrizeDao(),
	}
)

// Fill with you ideas below.
