// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalQuestConfigDao is internal type for wrapping internal DAO implements.
type internalQuestConfigDao = *internal.QuestConfigDao

// questConfigDao is the data access object for table quest_config.
// You can define custom methods on it to extend its functionality as you wish.
type questConfigDao struct {
	internalQuestConfigDao
}

var (
	// QuestConfig is globally public accessible object for table quest_config operations.
	QuestConfig = questConfigDao{
		internal.NewQuestConfigDao(),
	}
)

// Fill with you ideas below.
