// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalQuestUserDetailDao is internal type for wrapping internal DAO implements.
type internalQuestUserDetailDao = *internal.QuestUserDetailDao

// questUserDetailDao is the data access object for table quest_user_detail.
// You can define custom methods on it to extend its functionality as you wish.
type questUserDetailDao struct {
	internalQuestUserDetailDao
}

var (
	// QuestUserDetail is globally public accessible object for table quest_user_detail operations.
	QuestUserDetail = questUserDetailDao{
		internal.NewQuestUserDetailDao(),
	}
)

// Fill with you ideas below.
