// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRechargePointsRecordDao is internal type for wrapping internal DAO implements.
type internalRechargePointsRecordDao = *internal.RechargePointsRecordDao

// rechargePointsRecordDao is the data access object for table recharge_points_record.
// You can define custom methods on it to extend its functionality as you wish.
type rechargePointsRecordDao struct {
	internalRechargePointsRecordDao
}

var (
	// RechargePointsRecord is globally public accessible object for table recharge_points_record operations.
	RechargePointsRecord = rechargePointsRecordDao{
		internal.NewRechargePointsRecordDao(),
	}
)

// Fill with you ideas below.
