// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRedEnvelopeInfoDao is internal type for wrapping internal DAO implements.
type internalRedEnvelopeInfoDao = *internal.RedEnvelopeInfoDao

// redEnvelopeInfoDao is the data access object for table red_envelope_info.
// You can define custom methods on it to extend its functionality as you wish.
type redEnvelopeInfoDao struct {
	internalRedEnvelopeInfoDao
}

var (
	// RedEnvelopeInfo is globally public accessible object for table red_envelope_info operations.
	RedEnvelopeInfo = redEnvelopeInfoDao{
		internal.NewRedEnvelopeInfoDao(),
	}
)

// Fill with you ideas below.
