// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRedEnvelopeRecordDao is internal type for wrapping internal DAO implements.
type internalRedEnvelopeRecordDao = *internal.RedEnvelopeRecordDao

// redEnvelopeRecordDao is the data access object for table red_envelope_record.
// You can define custom methods on it to extend its functionality as you wish.
type redEnvelopeRecordDao struct {
	internalRedEnvelopeRecordDao
}

var (
	// RedEnvelopeRecord is globally public accessible object for table red_envelope_record operations.
	RedEnvelopeRecord = redEnvelopeRecordDao{
		internal.NewRedEnvelopeRecordDao(),
	}
)

// Fill with you ideas below.
