// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalReportRecordDao is internal type for wrapping internal DAO implements.
type internalReportRecordDao = *internal.ReportRecordDao

// reportRecordDao is the data access object for table report_record.
// You can define custom methods on it to extend its functionality as you wish.
type reportRecordDao struct {
	internalReportRecordDao
}

var (
	// ReportRecord is globally public accessible object for table report_record operations.
	ReportRecord = reportRecordDao{
		internal.NewReportRecordDao(),
	}
)

// Fill with you ideas below.
