// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRewardRecordDao is internal type for wrapping internal DAO implements.
type internalRewardRecordDao = *internal.RewardRecordDao

// rewardRecordDao is the data access object for table reward_record.
// You can define custom methods on it to extend its functionality as you wish.
type rewardRecordDao struct {
	internalRewardRecordDao
}

var (
	// RewardRecord is globally public accessible object for table reward_record operations.
	RewardRecord = rewardRecordDao{
		internal.NewRewardRecordDao(),
	}
)

// Fill with you ideas below.
