// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRoomRemoveListDao is internal type for wrapping internal DAO implements.
type internalRoomRemoveListDao = *internal.RoomRemoveListDao

// roomRemoveListDao is the data access object for table room_remove_list.
// You can define custom methods on it to extend its functionality as you wish.
type roomRemoveListDao struct {
	internalRoomRemoveListDao
}

var (
	// RoomRemoveList is globally public accessible object for table room_remove_list operations.
	RoomRemoveList = roomRemoveListDao{
		internal.NewRoomRemoveListDao(),
	}
)

// Fill with you ideas below.
