// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRoomMultipleUserDao is internal type for wrapping internal DAO implements.
type internalRoomMultipleUserDao = *internal.RoomMultipleUserDao

// roomMultipleUserDao is the data access object for table room_multiple_user.
// You can define custom methods on it to extend its functionality as you wish.
type roomMultipleUserDao struct {
	internalRoomMultipleUserDao
}

var (
	// RoomMultipleUser is globally public accessible object for table room_multiple_user operations.
	RoomMultipleUser = roomMultipleUserDao{
		internal.NewRoomMultipleUserDao(),
	}
)

// Fill with you ideas below.
