// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRoomUnlockRecordDao is internal type for wrapping internal DAO implements.
type internalRoomUnlockRecordDao = *internal.RoomUnlockRecordDao

// roomUnlockRecordDao is the data access object for table room_unlock_record.
// You can define custom methods on it to extend its functionality as you wish.
type roomUnlockRecordDao struct {
	internalRoomUnlockRecordDao
}

var (
	// RoomUnlockRecord is globally public accessible object for table room_unlock_record operations.
	RoomUnlockRecord = roomUnlockRecordDao{
		internal.NewRoomUnlockRecordDao(),
	}
)

// Fill with you ideas below.
