// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRoomAdminDao is internal type for wrapping internal DAO implements.
type internalRoomAdminDao = *internal.RoomAdminDao

// roomAdminDao is the data access object for table room_admin.
// You can define custom methods on it to extend its functionality as you wish.
type roomAdminDao struct {
	internalRoomAdminDao
}

var (
	// RoomAdmin is globally public accessible object for table room_admin operations.
	RoomAdmin = roomAdminDao{
		internal.NewRoomAdminDao(),
	}
)

// Fill with you ideas below.
