// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRoomActivityBannerDao is internal type for wrapping internal DAO implements.
type internalRoomActivityBannerDao = *internal.RoomActivityBannerDao

// roomActivityBannerDao is the data access object for table room_activity_banner.
// You can define custom methods on it to extend its functionality as you wish.
type roomActivityBannerDao struct {
	internalRoomActivityBannerDao
}

var (
	// RoomActivityBanner is globally public accessible object for table room_activity_banner operations.
	RoomActivityBanner = roomActivityBannerDao{
		internal.NewRoomActivityBannerDao(),
	}
)

// Fill with you ideas below.
