// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRoomReviewRecordDao is internal type for wrapping internal DAO implements.
type internalRoomReviewRecordDao = *internal.RoomReviewRecordDao

// roomReviewRecordDao is the data access object for table room_review_record.
// You can define custom methods on it to extend its functionality as you wish.
type roomReviewRecordDao struct {
	internalRoomReviewRecordDao
}

var (
	// RoomReviewRecord is globally public accessible object for table room_review_record operations.
	RoomReviewRecord = roomReviewRecordDao{
		internal.NewRoomReviewRecordDao(),
	}
)

// Fill with you ideas below.
