// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRoomLiveBattleDao is internal type for wrapping internal DAO implements.
type internalRoomLiveBattleDao = *internal.RoomLiveBattleDao

// roomLiveBattleDao is the data access object for table room_live_battle.
// You can define custom methods on it to extend its functionality as you wish.
type roomLiveBattleDao struct {
	internalRoomLiveBattleDao
}

var (
	// RoomLiveBattle is globally public accessible object for table room_live_battle operations.
	RoomLiveBattle = roomLiveBattleDao{
		internal.NewRoomLiveBattleDao(),
	}
)

// Fill with you ideas below.
