// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRoomUserRecordDao is internal type for wrapping internal DAO implements.
type internalRoomUserRecordDao = *internal.RoomUserRecordDao

// roomUserRecordDao is the data access object for table room_user_record.
// You can define custom methods on it to extend its functionality as you wish.
type roomUserRecordDao struct {
	internalRoomUserRecordDao
}

var (
	// RoomUserRecord is globally public accessible object for table room_user_record operations.
	RoomUserRecord = roomUserRecordDao{
		internal.NewRoomUserRecordDao(),
	}
)

// Fill with you ideas below.
