// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRoomLiveCallDao is internal type for wrapping internal DAO implements.
type internalRoomLiveCallDao = *internal.RoomLiveCallDao

// roomLiveCallDao is the data access object for table room_live_call.
// You can define custom methods on it to extend its functionality as you wish.
type roomLiveCallDao struct {
	internalRoomLiveCallDao
}

var (
	// RoomLiveCall is globally public accessible object for table room_live_call operations.
	RoomLiveCall = roomLiveCallDao{
		internal.NewRoomLiveCallDao(),
	}
)

// Fill with you ideas below.
