// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalRoomLiveDao is internal type for wrapping internal DAO implements.
type internalRoomLiveDao = *internal.RoomLiveDao

// roomLiveDao is the data access object for table room_live.
// You can define custom methods on it to extend its functionality as you wish.
type roomLiveDao struct {
	internalRoomLiveDao
}

var (
	// RoomLive is globally public accessible object for table room_live operations.
	RoomLive = roomLiveDao{
		internal.NewRoomLiveDao(),
	}
)

// Fill with you ideas below.
