// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalSafeInfoDao is internal type for wrapping internal DAO implements.
type internalSafeInfoDao = *internal.SafeInfoDao

// safeInfoDao is the data access object for table safe_info.
// You can define custom methods on it to extend its functionality as you wish.
type safeInfoDao struct {
	internalSafeInfoDao
}

var (
	// SafeInfo is globally public accessible object for table safe_info operations.
	SafeInfo = safeInfoDao{
		internal.NewSafeInfoDao(),
	}
)

// Fill with you ideas below.
