// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalServerGuildLiveStatisticsDao is internal type for wrapping internal DAO implements.
type internalServerGuildLiveStatisticsDao = *internal.ServerGuildLiveStatisticsDao

// serverGuildLiveStatisticsDao is the data access object for table server_guild_live_statistics.
// You can define custom methods on it to extend its functionality as you wish.
type serverGuildLiveStatisticsDao struct {
	internalServerGuildLiveStatisticsDao
}

var (
	// ServerGuildLiveStatistics is globally public accessible object for table server_guild_live_statistics operations.
	ServerGuildLiveStatistics = serverGuildLiveStatisticsDao{
		internal.NewServerGuildLiveStatisticsDao(),
	}
)

// Fill with you ideas below.
