// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalServerNoticeDao is internal type for wrapping internal DAO implements.
type internalServerNoticeDao = *internal.ServerNoticeDao

// serverNoticeDao is the data access object for table server_notice.
// You can define custom methods on it to extend its functionality as you wish.
type serverNoticeDao struct {
	internalServerNoticeDao
}

var (
	// ServerNotice is globally public accessible object for table server_notice operations.
	ServerNotice = serverNoticeDao{
		internal.NewServerNoticeDao(),
	}
)

// Fill with you ideas below.
