// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalServerWeekStatisticsDao is internal type for wrapping internal DAO implements.
type internalServerWeekStatisticsDao = *internal.ServerWeekStatisticsDao

// serverWeekStatisticsDao is the data access object for table server_week_statistics.
// You can define custom methods on it to extend its functionality as you wish.
type serverWeekStatisticsDao struct {
	internalServerWeekStatisticsDao
}

var (
	// ServerWeekStatistics is globally public accessible object for table server_week_statistics operations.
	ServerWeekStatistics = serverWeekStatisticsDao{
		internal.NewServerWeekStatisticsDao(),
	}
)

// Fill with you ideas below.
