// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalShopGoodsDao is internal type for wrapping internal DAO implements.
type internalShopGoodsDao = *internal.ShopGoodsDao

// shopGoodsDao is the data access object for table shop_goods.
// You can define custom methods on it to extend its functionality as you wish.
type shopGoodsDao struct {
	internalShopGoodsDao
}

var (
	// ShopGoods is globally public accessible object for table shop_goods operations.
	ShopGoods = shopGoodsDao{
		internal.NewShopGoodsDao(),
	}
)

// Fill with you ideas below.
