// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalShopOrderDao is internal type for wrapping internal DAO implements.
type internalShopOrderDao = *internal.ShopOrderDao

// shopOrderDao is the data access object for table shop_order.
// You can define custom methods on it to extend its functionality as you wish.
type shopOrderDao struct {
	internalShopOrderDao
}

var (
	// ShopOrder is globally public accessible object for table shop_order operations.
	ShopOrder = shopOrderDao{
		internal.NewShopOrderDao(),
	}
)

// Fill with you ideas below.
