// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalStarLevelResetConfigDao is internal type for wrapping internal DAO implements.
type internalStarLevelResetConfigDao = *internal.StarLevelResetConfigDao

// starLevelResetConfigDao is the data access object for table star_level_reset_config.
// You can define custom methods on it to extend its functionality as you wish.
type starLevelResetConfigDao struct {
	internalStarLevelResetConfigDao
}

var (
	// StarLevelResetConfig is globally public accessible object for table star_level_reset_config operations.
	StarLevelResetConfig = starLevelResetConfigDao{
		internal.NewStarLevelResetConfigDao(),
	}
)

// Fill with you ideas below.
