// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalSyncTaskDao is internal type for wrapping internal DAO implements.
type internalSyncTaskDao = *internal.SyncTaskDao

// syncTaskDao is the data access object for table sync_task.
// You can define custom methods on it to extend its functionality as you wish.
type syncTaskDao struct {
	internalSyncTaskDao
}

var (
	// SyncTask is globally public accessible object for table sync_task operations.
	SyncTask = syncTaskDao{
		internal.NewSyncTaskDao(),
	}
)

// Fill with you ideas below.
