// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalSysAdminRoleDao is internal type for wrapping internal DAO implements.
type internalSysAdminRoleDao = *internal.SysAdminRoleDao

// sysAdminRoleDao is the data access object for table sys_admin_role.
// You can define custom methods on it to extend its functionality as you wish.
type sysAdminRoleDao struct {
	internalSysAdminRoleDao
}

var (
	// SysAdminRole is globally public accessible object for table sys_admin_role operations.
	SysAdminRole = sysAdminRoleDao{
		internal.NewSysAdminRoleDao(),
	}
)

// Fill with you ideas below.
