// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalSysServerRoleDao is internal type for wrapping internal DAO implements.
type internalSysServerRoleDao = *internal.SysServerRoleDao

// sysServerRoleDao is the data access object for table sys_server_role.
// You can define custom methods on it to extend its functionality as you wish.
type sysServerRoleDao struct {
	internalSysServerRoleDao
}

var (
	// SysServerRole is globally public accessible object for table sys_server_role operations.
	SysServerRole = sysServerRoleDao{
		internal.NewSysServerRoleDao(),
	}
)

// Fill with you ideas below.
