// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalThirdPartyBusiGameOrderDao is internal type for wrapping internal DAO implements.
type internalThirdPartyBusiGameOrderDao = *internal.ThirdPartyBusiGameOrderDao

// thirdPartyBusiGameOrderDao is the data access object for table third_party_busi_game_order.
// You can define custom methods on it to extend its functionality as you wish.
type thirdPartyBusiGameOrderDao struct {
	internalThirdPartyBusiGameOrderDao
}

var (
	// ThirdPartyBusiGameOrder is globally public accessible object for table third_party_busi_game_order operations.
	ThirdPartyBusiGameOrder = thirdPartyBusiGameOrderDao{
		internal.NewThirdPartyBusiGameOrderDao(),
	}
)

// Fill with you ideas below.
