// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalTopicInfoDao is internal type for wrapping internal DAO implements.
type internalTopicInfoDao = *internal.TopicInfoDao

// topicInfoDao is the data access object for table topic_info.
// You can define custom methods on it to extend its functionality as you wish.
type topicInfoDao struct {
	internalTopicInfoDao
}

var (
	// TopicInfo is globally public accessible object for table topic_info operations.
	TopicInfo = topicInfoDao{
		internal.NewTopicInfoDao(),
	}
)

// Fill with you ideas below.
