// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalTradesInfoDao is internal type for wrapping internal DAO implements.
type internalTradesInfoDao = *internal.TradesInfoDao

// tradesInfoDao is the data access object for table trades_info.
// You can define custom methods on it to extend its functionality as you wish.
type tradesInfoDao struct {
	internalTradesInfoDao
}

var (
	// TradesInfo is globally public accessible object for table trades_info operations.
	TradesInfo = tradesInfoDao{
		internal.NewTradesInfoDao(),
	}
)

// Fill with you ideas below.
