// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalUpdateRecordDao is internal type for wrapping internal DAO implements.
type internalUpdateRecordDao = *internal.UpdateRecordDao

// updateRecordDao is the data access object for table update_record.
// You can define custom methods on it to extend its functionality as you wish.
type updateRecordDao struct {
	internalUpdateRecordDao
}

var (
	// UpdateRecord is globally public accessible object for table update_record operations.
	UpdateRecord = updateRecordDao{
		internal.NewUpdateRecordDao(),
	}
)

// Fill with you ideas below.
