// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalUserBankDao is internal type for wrapping internal DAO implements.
type internalUserBankDao = *internal.UserBankDao

// userBankDao is the data access object for table user_bank.
// You can define custom methods on it to extend its functionality as you wish.
type userBankDao struct {
	internalUserBankDao
}

var (
	// UserBank is globally public accessible object for table user_bank operations.
	UserBank = userBankDao{
		internal.NewUserBankDao(),
	}
)

// Fill with you ideas below.
