// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalUserBattleMatchDao is internal type for wrapping internal DAO implements.
type internalUserBattleMatchDao = *internal.UserBattleMatchDao

// userBattleMatchDao is the data access object for table user_battle_match.
// You can define custom methods on it to extend its functionality as you wish.
type userBattleMatchDao struct {
	internalUserBattleMatchDao
}

var (
	// UserBattleMatch is globally public accessible object for table user_battle_match operations.
	UserBattleMatch = userBattleMatchDao{
		internal.NewUserBattleMatchDao(),
	}
)

// Fill with you ideas below.
