// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalUserDressUpLogDao is internal type for wrapping internal DAO implements.
type internalUserDressUpLogDao = *internal.UserDressUpLogDao

// userDressUpLogDao is the data access object for table user_dress_up_log.
// You can define custom methods on it to extend its functionality as you wish.
type userDressUpLogDao struct {
	internalUserDressUpLogDao
}

var (
	// UserDressUpLog is globally public accessible object for table user_dress_up_log operations.
	UserDressUpLog = userDressUpLogDao{
		internal.NewUserDressUpLogDao(),
	}
)

// Fill with you ideas below.
