// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"fuya-ark/internal/dao/internal"
)

// internalUserBaseInfoDao is internal type for wrapping internal DAO implements.
type internalUserBaseInfoDao = *internal.UserBaseInfoDao

// userBaseInfoDao is the data access object for table user_base_info.
// You can define custom methods on it to extend its functionality as you wish.
type userBaseInfoDao struct {
	internalUserBaseInfoDao
}

var (
	// UserBaseInfo is globally public accessible object for table user_base_info operations.
	UserBaseInfo = userBaseInfoDao{
		internal.NewUserBaseInfoDao(),
	}
)

// Fill with you ideas below.
